Real-Time Temperature Prediction

In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder , StandardScaler , OneHotEncoder

In [3]:
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\IndianWeatherRepository.csv")

In [4]:
df1 =  df[['latitude', 'longitude','timezone' ,'temperature_celsius', 'condition_text','wind_kph', 'pressure_in','humidity','cloud']]

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,12.6,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,10.7,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,16.8,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,4.9,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,11.4,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3819,India,Niwari,Uttar Pradesh,28.88,77.53,Asia/Kolkata,1693784700,2023-09-04 05:15,28.0,82.4,...,70.3,123.1,4,9,05:59 AM,06:40 PM,08:56 PM,09:18 AM,Waning Gibbous,88
3820,India,Saitual,Mizoram,23.97,92.58,Asia/Kolkata,1693784700,2023-09-04 05:15,19.4,66.9,...,7.9,8.6,1,1,05:02 AM,05:37 PM,07:59 PM,08:11 AM,Waning Gibbous,88
3821,India,Ranipet,Tamil Nadu,12.93,79.33,Asia/Kolkata,1693784700,2023-09-04 05:15,25.9,78.6,...,3.7,5.9,1,1,06:02 AM,06:22 PM,09:04 PM,08:58 AM,Waning Gibbous,88
3822,India,Tenkasi,Tamil Nadu,8.97,77.30,Asia/Kolkata,1693784700,2023-09-04 05:15,24.1,75.4,...,2.0,2.3,1,1,06:12 AM,06:28 PM,09:16 PM,09:04 AM,Waning Gibbous,88
3823,India,Pendra,Maharashtra,21.93,74.15,Asia/Kolkata,1693784700,2023-09-04 05:15,24.2,75.6,...,11.3,16.5,1,1,06:17 AM,06:49 PM,09:17 PM,09:26 AM,Waning Gibbous,88

In [33]:
df1

,latitude,longitude,timezone,temperature_celsius,condition_text,wind_kph,pressure_in,humidity,cloud
0,24.57,77.72,Asia/Kolkata,27.5,Partly cloudy,20.5,29.77,67,26
1,23.33,77.80,Asia/Kolkata,27.5,Sunny,15.5,29.78,70,19
2,22.07,78.93,Asia/Kolkata,26.3,Partly cloudy,18.4,29.78,70,51
3,21.86,77.93,Asia/Kolkata,25.6,Cloudy,16.9,29.80,76,65
4,22.75,77.72,Asia/Kolkata,27.2,Cloudy,16.2,29.79,74,82
...,...,...,...,...,...,...,...,...,...
3819,28.88,77.53,Asia/Kolkata,28.0,Mist,6.1,29.62,79,0
3820,23.97,92.58,Asia/Kolkata,19.4,Light rain shower,3.6,29.66,99,73
3821,12.93,79.33,Asia/Kolkata,25.9,Light rain shower,23.0,29.65,76,56
3822,8.97,77.30,Asia/Kolkata,24.1,Cloudy,13.3,29.76,89,74
3823,21.93,74.15,Asia/Kolkata,24.2,Clear,10.4,29.70,85,11

In [34]:
print(df1.duplicated().sum())

# df1 = df1.drop_duplicates()

30

In [35]:
X = df1.drop(columns = ["temperature_celsius"] , axis = 1)
y = df1["temperature_celsius"]

In [36]:
cat = X.select_dtypes(include="object").columns
num = X.select_dtypes(exclude="object").columns

In [37]:
from sklearn.compose import ColumnTransformer 
pre = ColumnTransformer(
    transformers=[
        ("cat"  , OneHotEncoder(handle_unknown="ignore"  , drop = "first"), cat),
        ("num" , StandardScaler() , num)
        
    ]
)
pre

ColumnTransformer(transformers=[('cat',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 Index(['timezone', 'condition_text'], dtype='object')),
                                ('num', StandardScaler(),
                                 Index(['latitude', 'longitude', 'wind_kph', 'pressure_in', 'humidity',
       'cloud'],
      dtype='object'))])

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor


# model = Pipeline(steps= [
#     ("preporcesser", pre),
#     ("linear" , LinearRegression())
# ])

from sklearn.pipeline import Pipeline

model = Pipeline([
    ('preprocessor', pre),
    ('regressor', RandomForestRegressor(
        n_estimators=200,
    max_depth=10,              # tree depth limit
    min_samples_split=10,      # split ke liye min samples
    min_samples_leaf=5,        # leaf me min data
    random_state=42
    ))
])
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['timezone', 'condition_text'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['latitude', 'longitude', 'wind_kph', 'pressure_in', 'humidity',
       'cloud'],
      dtype='object'))])),
                ('regressor',
                 RandomForestRegressor(max_depth=10, min_samples_leaf=5,
                                       min_samples_split=10, n_estimators=200,
                                       random_state=42))])

In [39]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y , test_size=.2 ,random_state=42)

In [40]:
from sklearn.metrics import r2_score

In [41]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['timezone', 'condition_text'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['latitude', 'longitude', 'wind_kph', 'pressure_in', 'humidity',
       'cloud'],
      dtype='object'))])),
                ('regressor',
                 RandomForestRegressor(max_depth=10, min_samples_leaf=5,
                                       min_samples_split=10, n_estimators=200,
                                       random_state=42))])

In [42]:
y_pred = model.predict(X_test)
y_pred2 = model.predict(X_train)

In [43]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)

acc1 = r2_score(y_test, y_pred)   # ✅ correct order
acc2= r2_score(y_train, y_pred2)   # ✅ correct order
print("R2 Score (test):", acc1)
print("R2 Score (train):", acc2)

R2 Score (test): 0.8924886970654506
R2 Score (train): 0.9253655145778025

In [44]:
import joblib 

joblib.dump(model, "weather_model.pkl")

['weather_model.pkl']

In [45]:
import joblib 
import streamlit as st

model = joblib.load("weather_model.pkl")

st.title("Weather Temperature Prediction")

#input
latitude = st.number_input("Latitude (north or south(°)) :")
longitude = st.number_input("Longitude (east or west(°)) :")

timezone = st.selectbox("Timezone", ["Asia/Kolkata"])

condition = st.selectbox("Condition", ["Sunny", "Cloudy", "Partly cloudy"])

wind_kph = st.number_input("Wind Speed (kph)")
pressure_in = st.number_input("Pressure (in)")
humidity = st.slider("Humidity", 0, 100)
cloud = st.slider("Cloud", 0, 100)

# predict
if st.button("Predict Temperature"):

    live = pd.DataFrame({
        'latitude':[latitude], 
        'longitude':[longitude], 
        'timezone':[timezone],
        'condition_text':[condition], 
        'wind_kph':[wind_kph], 
        'pressure_in':[pressure_in], 
        'humidity':[humidity], 
        'cloud':[cloud]
    })

    prediction = model.predict(live)

    st.success(f"🌡️ Predicted Temperature: {prediction[0]:.2f} °C")

2026-04-28 10:20:06.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.803 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.803 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.810 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-28 10:20:06.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.